output_dir: "results"
seed: 10
task: "REDDIT"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    path: "data/reddit/results/out_final_formatted.jsonl"
    outpath: "predicted_gpt35_no_system.jsonl"
    system_prompt: "You are a helpful assistant that follows instructions precisely and accurately."
    profile_filter:
      hardness: 1
      certainty: 1
      num_tokens: 3000
    eval: False
gen_model:
  name: "gpt-3.5-turbo-16k-0613"
  provider: "openai"
  args: {
    temperature: 0.1
  }
