output_dir: "results/results_acs"
seed: 10
task: "ACS"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    outer_prompt:
        num_answers: 3
        num_shots: 0
        use_qa: False
        cot: True
    state: "NY"
    given_attrs: ["PUMA", "PINCP", "CIT"]
    target: "POBP"
    total_queries: 7
    creativity: 0.0
    complexity: 0.0
    level: 2
    lm_finetune: False
gen_model: 
  name: "gpt-4"
  provider: "openai"
  args: {}